CREATE TABLE IF NOT EXISTS stocks (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  symbol VARCHAR(64) NOT NULL UNIQUE,
  last_close DECIMAL(12,2) NOT NULL DEFAULT 0,
  high_52w  DECIMAL(12,2) NOT NULL DEFAULT 0,
  low_52w DECIMAL(12,2) NOT NULL DEFAULT 0,
  percent_diff DECIMAL(12,2) NOT NULL DEFAULT 0,
  is_active tinyint(1) DEFAULT 1,
  notes VARCHAR(1024) DEFAULT NULL,
  cur_date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
